services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0 # Set to 1 for development
    restart: unless-stopped
    env_file:
      - backend/.env
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    restart: unless-stopped
    networks:
      - default
    env_file:
      - frontend/.env.local

networks:
  default:
    driver: bridge
