services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0 # Set to 1 for development
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
